import X8Core

/// Coordinates the provider-neutral purge planning and execution phases.
///
/// The service deliberately exposes two operations: `plan` is side-effect-free
/// selection, while `execute` requires explicit confirmation and revalidates
/// revisions through the administration capability. It contains purge policy
/// but no provider SDK, CLI parsing, output formatting, or confirmation UI.
package struct CachePurgeService: Sendable {
    private let planner: CachePurgePlanner
    private let executor: CachePurgeExecutor

    /// Creates a purge service with the capabilities available for a backend.
    ///
    /// - Parameters:
    ///   - actionCacheStore: Required for the `cas` scope, which derives its
    ///     live root set from current Action Cache values.
    ///   - actionCacheRootExtractor: Decodes one Action Cache value into its
    ///     CAS roots, or `nil` when the value's layout is unrecognized. Kept
    ///     as an injected closure so this module stays free of the protobuf
    ///     types that decode it.
    package init(
        administration: any CacheAdministration,
        referenceReader: (any CASReferenceReader)? = nil,
        retentionStore: (any CASRetentionStore)? = nil,
        actionCacheStore: (any ActionCacheStore)? = nil,
        actionCacheRootExtractor: (@Sendable (ActionCacheValue) throws -> [CASDataID]?)? = nil
    ) {
        planner = CachePurgePlanner(
            administration: administration,
            referenceReader: referenceReader,
            retentionStore: retentionStore,
            actionCacheStore: actionCacheStore,
            actionCacheRootExtractor: actionCacheRootExtractor
        )
        executor = CachePurgeExecutor(administration: administration)
    }

    /// Builds a dry-run plan without deleting anything.
    ///
    /// - Returns: A snapshot of candidates and objects that were skipped by the
    ///   age, reachability, or metadata safety rules.
    package func plan(_ request: CachePurgeRequest) async throws -> CachePurgePlan {
        try await planner.plan(request)
    }

    /// Deletes only the exact objects in a previously generated plan.
    ///
    /// The executor performs a fresh listing and conditional revision checks;
    /// it never treats the plan as current merely because it was generated by
    /// this service.
    package func execute(
        _ plan: CachePurgePlan,
        confirm: Bool
    ) async throws -> CachePurgeResult {
        try await executor.execute(plan, confirm: confirm)
    }
}
